### ISSUE TITLE
Error during server.ts compilation

### ISSUE THREAD

**Issue by kos-mic-95** [OpenMined/PSI#118]
Hello! Im trying to compile-run the server.ts file, but i face the following issue:

![jvs error](https://user-images.githubusercontent.com/75835981/106507296-80feee80-64d3-11eb-8267-85626ebd0a77.png)

What can i do to overcome this problem?

**Comment by kos-mic-95** [comment]
Is there anyone that can help me to solve this issue ?

**Comment by schoppmp** [comment]
It seems you are using the deprecated psi.js library. See [here](https://github.com/OpenMined/PSI/blob/master/private_set_intersection/javascript/README.md) for how to install or build the new PSI library for JS/TS.

**Comment by kos-mic-95** [comment]
Thank you for your response! I am a bit confused! After running in cmd the commands " npm install @openmined/psi.js " and " import PSI from '@openmined/psi.js' ", what is the next step? Is there a way to run the program with commands in cmd or i have to buid a new library? what type o files do i have to create? .ts?and how many? should i put all of them in a new folder? 

Sorry for the long message and the number questions!

**Comment by schoppmp** [comment]
We currently don't have any commands / binaries, since this library is meant to be used as part of other projects, not standalone. You can find an example [here](https://github.com/OpenMined/PSI/blob/master/private_set_intersection/javascript/README.md#example), which runs both the client and the server. If you want to actually run PSI with two different parties, you'll have to split it up into a client and a server, and also handle the network connection. I'm not sure what your use case is, so it's hard to say something more specific here.

**Comment by kos-mic-95** [comment]
I want to use a two-party psi tool, in order to find the intersection of the elements of the two lists. In order to use the example you mentioned, is it enough to create 2 .ts files (client and server) and put each part of the code inside ?

**Comment by s0l0ist** [comment]
After you run `npm install @openmined/psi.js` you can use the library in your JS/TS applications.

By default, when you define an import `import PSI from '@openmined/psi.js'` it will load both client and server libraries for you to run the protocol in a single application.

In a real-world application, you would need to have two separate applications to communicate with each other. How you implement the communication between services is up to you. This library provides a means to serialize objects that can be sent across many means of communication, but any network transport is not a part of the library.
