### ISSUE TITLE
I have a few questions and look forward to the recovery of.

### ISSUE THREAD

**Issue by Cryptographer63** [OpenMined/PSI#132]
1. why choose ecdh instead of OT?
2. has a performance comparison been done with the oprf based kkrt16?
3. have tests with more than 10 million data been executed?
4. i want to use csv file as input, so how do i do it?

**Comment by s0l0ist** [comment]
> 1. why choose ecdh instead of OT?

For our PSI library, ECDH was chosen over OT because it was simpler to implement using widely available cryptographic libraries, namely private_join_and_compute.

> 2. has a performance comparison been done with the oprf based kkrt16?

Not against this repo that I am aware of.

> 3. have tests with more than 10 million data been executed?

No, but we have 1M server elems against different client bins. Our paper is old and benchmarks are different today, but it should give you an idea: https://arxiv.org/pdf/2011.09350

> 4. i want to use csv file as input, so how do i do it?

You would need to parse the csv, create a set and then pass it along. See the [python test](https://github.com/OpenMined/PSI/blob/master/private_set_intersection/python/tests.py)
