### ISSUE TITLE
Is there any plan to add support to Python 3.11+

### ISSUE THREAD

**Issue by YuanTingHsieh** [OpenMined/PSI#198]
## Question

Is there any plan to add support to Python 3.11+?

Thanks!

**Comment by s0l0ist** [comment]
I'll investigate.

**Comment by s0l0ist** [comment]
This is going to take some time as I cannot build on my M1 Mac and I don't have any other machines.

At a high level, this repo will need at the minimum:
- Refactor the WORKSPACE to Bzlmod
- Update build deps/platform compatibility to support ARM64 builds
- Fix any outdated rules

**Comment by s0l0ist** [comment]
Probably 4 weeks.

**Comment by s0l0ist** [comment]
@chesterxgchen, which version and arch do you need?

**Comment by s0l0ist** [comment]
Okay thank you. For initial testing 3.11 seems to work. 

But unfortunately, python 3.12 has some upstream issues which cause a segfault (on Mac arm64) and would take me longer to investigate. It is not clear yet if this affects other builds on Linux.

Once I've managed to get all builds migrated to the new Bazel toolchain (JS/WASM, Go, Rust, Python) working, I'll focus on 3.12 support.

Python is almost done.

**Comment by s0l0ist** [comment]
Marked as closed because the PR addresses 3.11; however, 3.12 is not yet working. The segfault is a bit more in-depth to solve/work around so I'd rather not spend time digging unless there's a pressing/absolute need for 3.12. My hope is that it will get fixed in the upstream deps in the near future.

**Comment by s0l0ist** [comment]
Eh publishing is failing, I'll dig some more and in the mean time re-open this issue.

**Comment by s0l0ist** [comment]
Hey all, once this has been merged there should be python packages for 3.11: https://github.com/OpenMined/PSI/pull/202

There is a python `v2.0.3` version, but there's a small chance that the wheel names were not published correctly due to a previous bug so the PR above addresses those inconsistencies by publishing new versions to PyPi.

## Install from PyPi
Install `v2.0.4`

```bash
pip install openmined-psi
```

## What's new?
- Support for Python 3.11 on Linux and MacOS 14+
- ARM support for MacOS 14+

**Comment by s0l0ist** [comment]
> please let me know when you ready to support python 3.12

sure, I'll have to periodically check to see if 3.12 tests compile/pass on my Mac. Once that works, then it is trivial to update the repository to publish 3.12 wheels

**Comment by s0l0ist** [comment]
Yes, that is intended and mentioned in the release notes. It appears that the python package naming convention has changed and the Bazel rules reflect the new normalization format.

**Comment by s0l0ist** [comment]
Amazing - let me know if there are any issues.

**Comment by s0l0ist** [comment]
Yes on macOS 14+.

**Comment by s0l0ist** [comment]
cc @chesterxgchen: https://github.com/OpenMined/PSI/pull/203

**Comment by s0l0ist** [comment]
@chesterxgchen - The definitions are correct because that task specifically handles publishing for the 'legacy' Python versions, where the patch version is `3.X.0`. This approach is mainly for older Linux systems, where users often install libraries using the default Python version that comes bundled with the system. It also addresses some edge cases related to the platform naming conventions on Linux.

Right below that task, I specify the Python version as `3.X`, which ensures that the latest patch version for each minor release (e.g., `3.X.Y`) is installed. This reflects what most users typically do when installing Python, as they usually prefer the latest available patch version. For instance, when installing Python via pyenv, users are likely aiming for the most up-to-date patch. The wheels built in this task also follow the more recent manylinux naming conventions for these versions of Python.

For more details on manylinux: https://github.com/pypa/manylinux
