### ISSUE TITLE
Failing build when applying PSI

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PSI#72]
## Description
The [PyVertical](https://github.com/OpenMined/PyVertical) project has applied the python PSI bindings.
Despite compiling locally, we are suddenly getting failing bazel builds on every build.
See [this build](https://github.com/OpenMined/PyVertical/runs/858292160?check_suite_focus=true), for example.

The issue is an incorrect checksum. We're not sure if the cause is:
- Incorrect implementation within PyVertical of PSI
- PSI
- pybind
- github CI's bazel

Our workspace file points to a specific commit of this repo, not master branch,
to avoid upstream breaking changes. I don't know yet whether that is a cause.

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.6, 3.7, 3.8

**Comment by schoppmp** [comment]
Thanks for reporting this!
The problem was that we pulled pybind11_bazel from a [branch](https://github.com/kerrick-lyft/pybind11_bazel/tree/py3) that was updated by the author, and we didn't pin the commit. The changes have landed in the [upstream repo](https://github.com/pybind/pybind11_bazel) for pybind11_bazel by now, so in #73 I fixed the issue by pinning the latest upstream commit.

**Comment by TTitcombe** [comment]
Thanks @schoppmp. Unfortunately we get another error - I'll open a new issue
